AWSTemplateFormatVersion: '2010-09-09'
Description: cloudfront resources
Parameters:
  SSLCertificateId:
    Type: String
    Description: SSLCertificateId
  Domain:
    Type: String
  ProjectName:
    Type: String
    Default: test

Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  CloudFrontResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: response-headers-policy
        Comment: security headers
        CorsConfig:
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - '*'
          AccessControlAllowMethods:
            Items:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
          AccessControlAllowOrigins:
            Items:
              - !Ref Domain
          AccessControlExposeHeaders:
            Items:
              - '*'
          AccessControlMaxAgeSec: 600
          OriginOverride: false
        CustomHeadersConfig:
          Items:
            - Header: Server # S3の場合 Server: AmazonS3 ヘッダが付くので隠す
              Value: ''
              Override: true
            - Header: X-Download-Options
              Value: noopen
              Override: false
            - Header: Cache-Control
              Value: no-store
              Override: false
            - Header: Pragma
              Value: no-cache
              Override: false
            - Header: Expires
              Value: -1
              Override: false
        SecurityHeadersConfig:
          FrameOptions:
            FrameOption: DENY
            Override: false
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: false
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: false
          ContentTypeOptions:
            Override: false
          ContentSecurityPolicy:
            ContentSecurityPolicy: frame-ancestors 'none'
            Override: false
          ReferrerPolicy:
            ReferrerPolicy: same-origin
            Override: false

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref Domain
        Comment: !Sub ${AWS::StackName} distribution
        DefaultRootObject: index.html
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
          AcmCertificateArn: !Ref SSLCertificateId
        Origins:
          - Id: S3BucketFrontendOrigin
            DomainName: {'Fn::ImportValue': !Join ['-', ['S3BucketFrontendDomainName', !Ref ProjectName]]}
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
          - Id: ApiGatewayOrigin
            DomainName: {'Fn::ImportValue': !Join ['-', ['ApiGatewayDomainName', !Ref ProjectName]]}
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: S3BucketFrontendOrigin
          ViewerProtocolPolicy: https-only
          ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
          Compress: true
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
        CacheBehaviors:
          -
            TargetOriginId: ApiGatewayOrigin
            PathPattern: /api/*
            ViewerProtocolPolicy: https-only
            ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            ForwardedValues:
              QueryString: true
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
        CustomErrorResponses:
          # 403 Access Denied 時にTOPのレスポンスを返すことによってspaとして動作させる
          -
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
            ErrorCachingMinTTL: 0
        IPV6Enabled: true
        Logging:
          Bucket: {'Fn::ImportValue': !Join ['-', ['S3BucketLogsDomainName', !Ref ProjectName]]}
          Prefix: cloudfront
          IncludeCookies: false

Outputs:
  CloudFrontDistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Join ['-', ['CloudFrontDistributionDomainName', !Ref ProjectName]]
  CloudFrontOriginAccessIdentity:
    Value: !Ref CloudFrontOriginAccessIdentity
    Export:
      Name: !Join ['-', ['CloudFrontOriginAccessIdentity', !Ref ProjectName]]
